[package]
name = "cpu-stats-logger"
description = "Tool to log CPU stats"
version = "0.1.0"
authors = ["Chris Atkin <atkinchris@gmail.com>"]
publish = false

[dependencies]
chrono = "0.4.9"
sysinfo = "0.9.5"
