[package]
name = "cpu-stats-logger"
description = "Tool to log CPU stats"
version = "0.1.0"
authors = ["Chris Atkin <atkinchris@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
chrono = "0.4.9"
sysinfo = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
